import type { AttributeCode, SpellDefinition } from "./types";

// Optolith-compatible IDs and checks; display names are German.
export const SPELLS: SpellDefinition[] = [
  { id: "SPELL_1", name: "Adlerauge", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_2", name: "Analys Arkanstruktur", check: ["KL", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_3", name: "Armatrutz", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_4", name: "Axxeleratus", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_5", name: "Balsam Salabunde", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_6", name: "Bannbaladin", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_7", name: "Blick in die Gedanken", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_8", name: "Blitz dich find", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_9", name: "Corpofesso", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_10", name: "Disruptivo", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_11", name: "Duplicatus", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_12", name: "Falkenauge", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_13", name: "Flim Flam", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_14", name: "Fulminictus", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_15", name: "Gardianum", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_16", name: "Große Gier", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_17", name: "Harmlose Gestalt", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_18", name: "Hexengalle", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_19", name: "Hexenkrallen", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_20", name: "Horriphobus", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_21", name: "Ignifaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_22", name: "Invocatio Minima", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_23", name: "Katzenaugen", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_24", name: "Krötensprung", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_25", name: "Manifesto", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_26", name: "Manus Miracula", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_27", name: "Motoricus", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_28", name: "Nebelwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_29", name: "Oculus Illusionis", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_30", name: "Odem Arcanum", check: ["KL", "IN", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_31", name: "Paralysis", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_32", name: "Penetrizzel", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_33", name: "Psychostabilis", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_34", name: "Radau", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_35", name: "Respondami", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_36", name: "Salander", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_37", name: "Sanftmut", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_38", name: "Satuarias Herrlichkeit", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_39", name: "Silentium", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_40", name: "Somnigravis", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_41", name: "Spinnenlauf", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_42", name: "Spurlos", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_43", name: "Transversalis", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_44", name: "Visibili", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_45", name: "Wasseratem", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_46", name: "Arcanovi", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_47", name: "Dschinnenruf", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_48", name: "Elementarer Diener", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_49", name: "Invocatio Maior", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_50", name: "Invocatio Minor", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_51", name: "Zauberklinge Geisterspeer", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_68", name: "Ängste lindern", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_69", name: "Atemnot", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_70", name: "Attributo (Körperkraft)", check: ["KL", "IN", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_71", name: "Claudibus", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_72", name: "Corpofrigo", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_73", name: "Dunkelheit", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_74", name: "Ecliptifactus", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_75", name: "Große Verwirrung", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_76", name: "Herr über das Tierreich", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_77", name: "Hexenholz", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_78", name: "Hexenknoten", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_79", name: "Höllenpein", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_80", name: "Ignisphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_81", name: "Klarum Purum", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_82", name: "Pestilenz erspüren", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_83", name: "Schlangenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_84", name: "Sensibar", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_85", name: "Sumus Elixiere", check: ["KL", "IN", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_86", name: "Vipernblick", check: ["MU", "MU", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_87", name: "Zunge betäuben", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_88", name: "Zwingtanz", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_89", name: "Ablativum", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_90", name: "Abvenenum", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_91", name: "Adlerschwinge", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_92", name: "Aeolito", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_93", name: "Alpgestalt", check: ["MU", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_94", name: "Altisonus", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_95", name: "Angst auslösen", check: ["MU", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_96", name: "Archofaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_97", name: "Archosphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_98", name: "Aromatis Illusionis", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_99", name: "Attributo (Charisma)", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_100", name: "Attributo (Fingerfertigkeit)", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_101", name: "Attributo (Klugheit)", check: ["KL", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_102", name: "Aufwecken", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_103", name: "Auge des Limbus", check: ["MU", "IN", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_104", name: "Aureolus", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_105", name: "Auris Illusionis", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_106", name: "Band und Fessel", check: ["KL", "CH", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_107", name: "Blick aufs Wesen", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_108", name: "Blindheit", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_109", name: "Chamaelioni", check: ["IN", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_110", name: "Dämonenbann", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_111", name: "Dämonenschild", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_112", name: "Debilitatio", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_113", name: "Desintegratus", check: ["KL", "CH", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_114", name: "Einflussbann", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_115", name: "Eisenrost", check: ["KL", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_116", name: "Elementarbann", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_117", name: "Elfenstimme", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_118", name: "Erinnerung verlasse dich", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_119", name: "Exposami", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_120", name: "Favilludo", check: ["IN", "FF", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_121", name: "Fischflosse", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_122", name: "Foramen", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_123", name: "Fortifex", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_124", name: "Gedankenbilder", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_125", name: "Gefunden", check: ["KL", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_126", name: "Haselbusch", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_127", name: "Heilungsbann", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_128", name: "Hellsichtbann", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_129", name: "Heptagramma", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_130", name: "Herzschlag ruhe", check: ["MU", "CH", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_131", name: "Hexagramma", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_132", name: "Ignorantia", check: ["IN", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_133", name: "Illusionsbann", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_134", name: "Imperavi", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_135", name: "Impersona", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_136", name: "Incendio", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_137", name: "Invercano", check: ["MU", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_138", name: "Karnifilo", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_139", name: "Kusch", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_140", name: "Last des Alters", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_141", name: "Lunge des Leviatan", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_142", name: "Manus Illusionis", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_143", name: "Memorans", check: ["KL", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_144", name: "Menetekel", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_145", name: "Nuntiovolo", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_146", name: "Objectobscuro", check: ["KL", "FF", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_147", name: "Objectofixo", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_148", name: "Objektbann", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_149", name: "Oculus Astralis", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_150", name: "Orcanofaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_151", name: "Orcanosphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_152", name: "Pentagramma", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_153", name: "Physiostabilis", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_154", name: "Plumbumbarum", check: ["MU", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_155", name: "Projectimago", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_156", name: "Reflectimago", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_157", name: "Regeneratio", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_158", name: "Sapefacta", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_159", name: "Schmerzen lindern", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_160", name: "Schwarz und Rot", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "TOU" },
  { id: "SPELL_161", name: "Schwarzer Schrecken", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_162", name: "Skelettarius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_163", name: "Solidirid", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_164", name: "Taubheit", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_165", name: "Telekinesebann", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_166", name: "Tiergedanken", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_167", name: "Verwandlungsbann", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_168", name: "Vogelzwitschern", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_169", name: "Wolfstatze", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_170", name: "Caldofrigo", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_171", name: "Nihilogravo", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_172", name: "Accuratum", check: ["KL", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "A" },
  { id: "SPELL_173", name: "Hagelschlag und Sturmgebrüll", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_174", name: "Hartes schmelze", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_175", name: "Leidensbund", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "A" },
  { id: "SPELL_176", name: "Magischer Raub", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_177", name: "Memorabia Falsifir", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_178", name: "Movimento", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "A" },
  { id: "SPELL_179", name: "Ruhe Körper", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_180", name: "Unberührt von Satinav", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_181", name: "Widerwille", check: ["KL", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_182", name: "Wirbelform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_183", name: "Xenographus", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "A" },
  { id: "SPELL_234", name: "Affenarme", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_235", name: "Affenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_236", name: "Arachnea", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_237", name: "Attributo (Gewandheit)", check: ["KL", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_238", name: "Attributo (Intuition)", check: ["KL", "IN", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_239", name: "Attributo (Mut)", check: ["KL", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_240", name: "Attributo (Konstitution)", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_241", name: "Avilea", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_242", name: "Basaltleib", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_243", name: "Brandungsleib", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_244", name: "Brennender Hass", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_245", name: "Dämonisches Vergessen", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_246", name: "Drachenleib", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_247", name: "Eichenleib", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_248", name: "Eigene Ängste", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_249", name: "Eigene Dummheit", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_250", name: "Eispfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_251", name: "Erzpfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_252", name: "Eulenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_253", name: "Federleib", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_254", name: "Feenstaub", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_255", name: "Feuerpfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_256", name: "Firnlauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_257", name: "Flammenwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_258", name: "Fledermausruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_259", name: "Frostleib", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_260", name: "Geisteressenz", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_261", name: "Gifthaut", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_262", name: "Glutlauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_263", name: "Hexenspeichel", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_264", name: "Hilfreiche Pfote", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_265", name: "Hilfreiche Schwinge", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_266", name: "Hilfreiche Tatze", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_267", name: "Himmelslauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_268", name: "Hornissenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_269", name: "Humuspfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_270", name: "Katzenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_271", name: "Krabbelnder Schrecken", check: ["MU", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_272", name: "Krähenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_273", name: "Kraft des Tieres", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_274", name: "Kulminatio", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_275", name: "Levthans Feuer", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_276", name: "Luftpfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_277", name: "Mal der Erschöpfung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_278", name: "Mal der Schwäche", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_279", name: "Objectovoco", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_280", name: "Pandaemonium", check: ["MU", "CH", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_281", name: "Pestodem", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_282", name: "Reptilea", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_283", name: "Sanfter Fall", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_284", name: "Schlechte Ausstrahlung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_285", name: "Schleier der Unwissenheit", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_286", name: "Seelentier erkennen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_287", name: "Seidenzunge", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A", checkModifier: "SPI" },
  { id: "SPELL_288", name: "Serpentialis", check: ["MU", "CH", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_289", name: "Spinnenruf", check: ["MU", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_290", name: "Standfest", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_291", name: "Steinwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_292", name: "Tiere besprechen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_293", name: "Unentflammbarkeit", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_294", name: "Ungeschickt", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_295", name: "Verunsicherung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_296", name: "Wasserpfeil", check: ["IN", "CH", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_297", name: "Weiches Erstarre", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_298", name: "Welle der Reinigung", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_299", name: "Welle des Schmerzes", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_300", name: "Wellenlauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_301", name: "Wipfellauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_302", name: "Wüstenlauf", check: ["MU", "KL", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_303", name: "Zauberpferd herbeirufen", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_304", name: "Adamantium", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "A" },
  { id: "SPELL_305", name: "Animatio", check: ["KL", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_306", name: "Band der Freundschaft", check: ["IN", "CH", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_307", name: "Bärenruhe", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_308", name: "Blick in die Vergangenheit", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_309", name: "Brandform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_310", name: "Custodosigil", check: ["MU", "KL", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_311", name: "Destructibo", check: ["KL", "KL", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_312", name: "Eins mit der Natur", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_313", name: "Ergebenheit der Wogen", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_314", name: "Erhabenheit des Marmors", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_315", name: "Felsenform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_316", name: "Freiheit der Wolken", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_317", name: "Geisterruf", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_318", name: "Geisterbeschwörung", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_319", name: "Gletscherform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_320", name: "Klarheit des Eises", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_321", name: "Körperlose Reise", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_322", name: "Madas Spiegel", check: ["MU", "KL", "IN"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_323", name: "Nekropathia", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_324", name: "Pflanzenform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_325", name: "Reinheit der Lohe", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_326", name: "Ruf der Feenwesen", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_327", name: "Seelenwanderung", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D", checkModifier: "\"SPI/TOU\"" },
  { id: "SPELL_328", name: "Standhafter Wächter", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_329", name: "Transmutare", check: ["IN", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_330", name: "Traumgestalt", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_331", name: "Überlegener Krieger", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_332", name: "Weisheit der Bäume", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_334", name: "Wogenform", check: ["KL", "FF", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_335", name: "Zaubernahrung", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_336", name: "Zauberschnurren", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_337", name: "Zauberwesen der Natur", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_338", name: "Zauberzwang", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_386", name: "Begehren erzeugen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_387", name: "Brustformung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_388", name: "Erregung spüren", check: ["IN", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_389", name: "Feuchte Erregung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_391", name: "Penisformung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_392", name: "Spielzeug der Lust", check: ["MU", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_393", name: "Vaginaformung", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_394", name: "Verlangen kontrollieren", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_395", name: "Abneigungen und Vorlieben erzeugen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_396", name: "Begierde auslösen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_397", name: "Übertragung der Liebeskünste", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_402", name: "Dämonenpakt beenden", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_403", name: "Aquafaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_404", name: "Aquasphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_405", name: "Aura der Erschöpfung", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_406", name: "Blitzball", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_407", name: "Böser Blick", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_408", name: "Dornenwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_409", name: "Eiswand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_410", name: "Erschöpfungen lindern", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_411", name: "Fesselfeld", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_412", name: "Frigifaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_413", name: "Frigisphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_414", name: "Halluzination", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_415", name: "Humofaxius", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_416", name: "Humosphaero", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "D" },
  { id: "SPELL_417", name: "Invinculo", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "TOU" },
  { id: "SPELL_418", name: "Nebelform", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_419", name: "Oktagramma", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_420", name: "Panik überkomme euch", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_421", name: "Schimmernder Schild", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_422", name: "Schuppenhaut", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_423", name: "Sphärenbann", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_424", name: "Sinesigil", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "A" },
  { id: "SPELL_425", name: "Sensattacco", check: ["MU", "IN", "GE"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_426", name: "Stillstand", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_427", name: "Sturm der Verunsicherung", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_428", name: "Sturmwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_429", name: "Temporalbann", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_430", name: "Tempus Stasis", check: ["MU", "KL", "KK"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_431", name: "Wellenwand", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_432", name: "Woge der Versteinerung", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "C" },
  { id: "SPELL_433", name: "Zorn der Elemente", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B" },
  { id: "SPELL_434", name: "Zweifel schüren", check: ["KL", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
  { id: "SPELL_435", name: "Applicatus", check: ["KL", "IN", "FF"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "B" },
  { id: "SPELL_436", name: "Blick durch fremde Augen", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C", checkModifier: "SPI" },
  { id: "SPELL_437", name: "Chimaeroform", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_438", name: "Chronoklassis", check: ["KL", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_439", name: "Chrononautos", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_440", name: "Gefäß der Jahre", check: ["MU", "KL", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_441", name: "Immortalis Lebenszeit", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_442", name: "Invocatio Maxima", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_443", name: "Infinitum Immerdar", check: ["KL", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_444", name: "Meister der Elemente", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_445", name: "Lawinenfall und Trümmerfeld", check: ["MU", "CH", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_446", name: "Planastrale", check: ["MU", "IN", "KO"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "D" },
  { id: "SPELL_447", name: "Stein wandle", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_448", name: "Totes handle", check: ["MU", "KL", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Ritual", improvementCost: "C" },
  { id: "SPELL_483", name: "Zitterfinger", check: ["MU", "IN", "CH"] as [AttributeCode, AttributeCode, AttributeCode], kind: "Zauber", improvementCost: "B", checkModifier: "SPI" },
];

export const SPELL_BY_ID = Object.fromEntries(SPELLS.map((entry) => [entry.id, entry])) as Record<string, SpellDefinition>;

export const CANTRIPS: Record<string, string> = {
  "CANTRIP_1": "Abkühlung",
  "CANTRIP_2": "Bauchreden",
  "CANTRIP_3": "Duft",
  "CANTRIP_4": "Feuerfinger",
  "CANTRIP_5": "Glücksgriff",
  "CANTRIP_6": "Handwärmer",
  "CANTRIP_7": "Lockruf",
  "CANTRIP_8": "Regenbogenaugen",
  "CANTRIP_9": "Schlangenhände",
  "CANTRIP_10": "Schnipsen",
  "CANTRIP_11": "Signatur",
  "CANTRIP_12": "Trocken",
  "CANTRIP_13": "Bartwuchs",
  "CANTRIP_14": "Beeren & Nüsse",
  "CANTRIP_15": "Hexenblick",
  "CANTRIP_16": "Kehrbesen",
  "CANTRIP_17": "Leselampe",
  "CANTRIP_18": "Pflanzenempathie",
  "CANTRIP_19": "Waffensäuberung",
  "CANTRIP_20": "Würze",
  "CANTRIP_21": "Aranische Rasur",
  "CANTRIP_22": "Beruhigung",
  "CANTRIP_23": "Blütenduft",
  "CANTRIP_24": "Ehrfürchtiges Verhalten",
  "CANTRIP_25": "Feenfüße",
  "CANTRIP_26": "Grußworte",
  "CANTRIP_27": "Guten Morgen",
  "CANTRIP_28": "Haarpracht",
  "CANTRIP_29": "Heller Stern",
  "CANTRIP_30": "Hintergrundmusik",
  "CANTRIP_31": "Insektenbann",
  "CANTRIP_32": "Luftstoß",
  "CANTRIP_33": "Nagellack",
  "CANTRIP_34": "Ordentlich",
  "CANTRIP_35": "Rohrstock",
  "CANTRIP_36": "Sandfigur",
  "CANTRIP_37": "Schminken",
  "CANTRIP_38": "Selbstarchivierung",
  "CANTRIP_39": "Tätowierung",
  "CANTRIP_40": "Unheimliches Lachen",
  "CANTRIP_41": "Wasserhöhe",
  "CANTRIP_42": "Weisheit des Leytfadens",
  "CANTRIP_43": "Zauberfeder",
  "CANTRIP_44": "Astrales Leuchten",
  "CANTRIP_45": "Auffälliger Stil",
  "CANTRIP_46": "Bereit zum Aufbruch",
  "CANTRIP_47": "Blick in den Limbus",
  "CANTRIP_48": "Dämonling",
  "CANTRIP_49": "Eiskalter Blick",
  "CANTRIP_50": "Elfenhaar",
  "CANTRIP_51": "Geistergeräusche",
  "CANTRIP_52": "Geräuschhexerei",
  "CANTRIP_53": "Heilsame Berührung",
  "CANTRIP_54": "Kleingeld",
  "CANTRIP_55": "Kneifen",
  "CANTRIP_56": "Konstante Temperatur",
  "CANTRIP_57": "Leuchtblume",
  "CANTRIP_58": "Putziges Tierchen",
  "CANTRIP_59": "Ruhige Ausstrahlung",
  "CANTRIP_60": "Rührlöffel",
  "CANTRIP_61": "Rutschiger Boden",
  "CANTRIP_62": "Schmutzabweisend",
  "CANTRIP_63": "Strahlendes Lächeln",
  "CANTRIP_64": "Tentakelgriff",
  "CANTRIP_65": "Tierpflege",
  "CANTRIP_66": "Tiertrick",
  "CANTRIP_67": "Verbundenheitsgefühl",
  "CANTRIP_68": "Verneigung",
  "CANTRIP_69": "Verrücktes Kichern",
  "CANTRIP_70": "Wohlgeruch",
  "CANTRIP_72": "Ausziehen von Zauberhand",
  "CANTRIP_73": "Erotischer Traum",
  "CANTRIP_74": "Lüsterne Hand",
  "CANTRIP_75": "Ölhaut",
  "CANTRIP_76": "Schamhaarfrisur",
  "CANTRIP_77": "Elementarling",
  "CANTRIP_78": "Feenzauber",
  "CANTRIP_79": "Hand der Antimagie",
  "CANTRIP_80": "Hundekeks",
  "CANTRIP_81": "Kleiner Fliegender Teppich",
  "CANTRIP_82": "Körperpflege",
  "CANTRIP_83": "Kriegsbemalung",
  "CANTRIP_84": "Laufendes Händchen",
  "CANTRIP_85": "Steinempathie",
  "CANTRIP_86": "Schattenspiel",
  "CANTRIP_87": "Siegel der Elemente",
  "CANTRIP_88": "Übergangen",
  "CANTRIP_89": "Wechselschein",
  "CANTRIP_90": "Aura der Eitelkeit",
  "CANTRIP_91": "Einfache Telekinese",
  "CANTRIP_92": "Essenz der Niederhöllen",
  "CANTRIP_93": "Feuerspiel",
  "CANTRIP_94": "Flammenhaar",
  "CANTRIP_95": "Sprechendes Kästchen",
  "CANTRIP_96": "Türklopfer",
  "CANTRIP_97": "Unauffälliger Stab",
  "CANTRIP_98": "Wind im Haar",
};

