// Namen aus den vollständigen Auswahllisten der offiziellen DSA-Regelwiki.
// Es werden ausschließlich Bezeichnungen gespeichert, keine Regeltexte.
export const REGELWIKI_ADVANTAGE_NAMES = [
  "Adel I-III",
  "Affinität zu Dämonen",
  "Affinität zu Elementaren",
  "Akoluth",
  "Allerweltsname",
  "Altersresistenz (*)",
  "Angenehmer Geruch",
  "Animalische Kraft",
  "Astralschutz",
  "Basiliskentöter",
  "Begabte/r Aufreißer/in",
  "Begabung",
  "Beidhändig",
  "Betörender Duft",
  "Biss I-III (*)",
  "Blumenduft",
  "Blutzauberer",
  "Dickes Fell",
  "Drachenblut (Einhorndrache)",
  "Drachenblut (Gletscherwurm)",
  "Drachenblut (Höhlendrache)",
  "Drachenblut (Kaiserdrache)",
  "Drachenblut (Purpurwurm)",
  "Drachenblut (Riesenlindwurm)",
  "Drachenkontrolle",
  "Drachenschwanz",
  "Drachentöter",
  "Drachenzauberkraft",
  "Dreistrahl",
  "Dschinnenblut (Eisdschinn)",
  "Dschinnenblut (Erzdschinn)",
  "Dschinnenblut (Feuerdschinn)",
  "Dschinnenblut (Humusdschinn)",
  "Dschinnenblut (Luftdschinn)",
  "Dschinnenblut (Rosendschinn)",
  "Dschinnenblut (Wasserdschinn)",
  "Dunkelsicht I-II (*)",
  "Einblicke ins Verborgene",
  "Einkommen I-VI",
  "Eisenaffine Aura",
  "Eisern",
  "Eiskalte Berührung",
  "Elementare Verteidigung",
  "Elementarhand",
  "Entfernungssinn",
  "Feenblut (Blütenfee)",
  "Feenblut (Dryade)",
  "Feenblut (Großer Biestinger)",
  "Feenblut (Holde)",
  "Feenblut (Nixer)",
  "Feenblut (Oreade)",
  "Feenblut (Satyr)",
  "Feenblut (Schwarzfee)",
  "Feenblut (Vila)",
  "Feenfreund",
  "Flammenhand",
  "Flink",
  "Fuchssinn",
  "Gabe der Sonne",
  "Geborener Redner",
  "Gedankensprache",
  "Geweihter",
  "Giftresistenz I-II",
  "Glatte Haut",
  "Glück I-III",
  "Gon",
  "Greifschwanz (*)",
  "Große Zauberauswahl I-II",
  "Gutaussehend I-II",
  "Gutes Namensgedächtnis",
  "Harmonie des Waldes",
  "Hart im Nehmen",
  "Hass auf",
  "Hauttasche (*)",
  "Heldenhafter Name",
  "Herausragende Fertigkeit",
  "Herausragende Kampftechnik",
  "Herausragender Sinn",
  "Hitzeresistenz",
  "Hohe Astralkraft I-VII",
  "Hohe Karmalkraft I-VII",
  "Hohe Lebenskraft I-VII",
  "Hohe Seelenkraft",
  "Hohe Zähigkeit",
  "Immunität gegen (Gift)",
  "Immunität gegen (Krankheit)",
  "Kälteresistenz",
  "Kein Bann des Eisens",
  "Koboldfreund",
  "Kontakt (Bettler)",
  "Kontakt (Botenreiter)",
  "Kontakt (Freund aus Kindheitstagen)",
  "Kontakt (Geweihte)",
  "Kontakt (Handwerksmeister)",
  "Kontakt (Hehler)",
  "Kontakt (Junkerin)",
  "Kontakt (Magier)",
  "Kontakt (Schmuggler)",
  "Kontakt (Sklavin)",
  "Kontakt (Soldat)",
  "Kontakt (Söldnerhauptmann)",
  "Kontakt (Stadtmagistrat)",
  "Kontakt (Stadtwache)",
  "Kontakt (Tempelvorsteherin)",
  "Kontakt (Unterweltkönig)",
  "Kontakt (Wirt)",
  "Kraft der Bäume",
  "Kraft des Drachen",
  "Krankheitsresistenz I-II",
  "Leichter Gang",
  "Limbussinn",
  "Machtvolle Zaubermelodien",
  "Machtvolle Zaubertänze",
  "Magische Einstimmung",
  "Majestätsstimme",
  "Muttererde",
  "Mystiker",
  "Natürliche Waffe (Biss) (*)",
  "Natürliche Waffe (Schwanz) (*)",
  "Natürlicher Rüstungsschutz I-II (*)",
  "Nichtschläfer (*)",
  "Odemwaffe",
  "Pragmatiker",
  "Prediger",
  "Rankenfessel",
  "Reich I-X",
  "Richtungssinn",
  "Sagaheld",
  "Saumagen I-II",
  "Schlangenmensch",
  "Schnell wieder auf den Beinen",
  "Schuppenkleid I-II",
  "Schutzgeist",
  "Schwer zu verzaubern (*)",
  "Schwingenpaar",
  "Seesprache",
  "Soziale Anpassungsfähigkeit",
  "Sphärennahrung",
  "Telepathieüberflutung",
  "Temperaturimmunität (Hitze oder Kälte)",
  "Tierfreund",
  "Tiergeistaura (Patron)",
  "Tierische Kampfgefährten",
  "Unbeschwertes Zaubern",
  "Unnachgiebigkeit der Berge",
  "Unscheinbar",
  "Unumstößlich",
  "Verbesserte Regeneration (Astralenergie) I-III",
  "Verbesserte Regeneration (Karmaenergie) I-III",
  "Verbesserte Regeneration (Lebensenergie) I-III",
  "Verführerische Gestalt",
  "Verhüllte Aura",
  "Verpuppung",
  "Vertrauenerweckend",
  "Visionär",
  "Waffenbegabung",
  "Walwut (Swafskari)",
  "Wasser des Lebens",
  "Wasserheilung",
  "Wasserlebewesen (*)",
  "Wegwehen",
  "Weitreichende Zaubermelodien I-III",
  "Weitreichende Zaubertänze I-III",
  "Wohlklang",
  "Wolfsblut",
  "Wolfsgebiss",
  "Wolfskind",
  "Zäher Hund",
  "Zahlreiche Predigten I-II",
  "Zahlreiche Visionen I-II",
  "Zauberer",
  "Zeitgefühl",
  "Zusätzliche Gliedmaßen (Schwanz) (*)",
  "Zweistimmiger Gesang (*)",
  "Zwergennase"
] as const;

export const REGELWIKI_DISADVANTAGE_NAMES = [
  "Angst vor … I-III",
  "Arm I-III",
  "Artefaktgebunden",
  "Behäbig",
  "Blind",
  "Blutrausch",
  "Böser Namensvetter",
  "Eingeschränkter Sinn",
  "Empfindlichkeit (unedle Metalle) (*)",
  "Farbenblind",
  "Fettleibig",
  "Friedlos",
  "Giftanfällig I-II",
  "Gläsern",
  "Hässlich I-II",
  "Hitzeempfindlich",
  "Hitzeempfindlich II (*)",
  "Instabiler Zauberer",
  "Jagdwildgeruch",
  "Kälteempfindlich",
  "Kältestarre (*)",
  "Kein Vertrauter (*)",
  "Keine Flugsalbe (*)",
  "Kleine Zauberauswahl I-III",
  "Körpergebundene Kraft",
  "Körperliche Auffälligkeit",
  "Krankheitsanfällig I-II",
  "Lächerlicher Name",
  "Lästige Blütenfeen",
  "Lästige Mindergeister",
  "Lernfaul",
  "Lichtempfindlich",
  "Lichtempfindlich II (*)",
  "Limbus-Medium I-II",
  "Magische Einschränkung",
  "Misslungene Reifeprüfung",
  "Nachtblind",
  "Niedrige Astralkraft I-VII",
  "Niedrige Karmalkraft I-VII",
  "Niedrige Lebenskraft I-VII",
  "Niedrige Seelenkraft",
  "Niedrige Zähigkeit",
  "Pech I-III",
  "Pechmagnet",
  "Persönlichkeitsschwäche",
  "Prinzipientreue I-III",
  "Raubtiergeruch",
  "Schlafwandler",
  "Schlechte Angewohnheit",
  "Schlechte Eigenschaft",
  "Schlechte Regeneration (Astralenergie) I-III",
  "Schlechte Regeneration (Karmaenergie) I-III",
  "Schlechte Regeneration (Lebensenergie) I-III",
  "Schlechtes Namensgedächtnis",
  "Schurkenname",
  "Schwache Zaubermelodien",
  "Schwache Zaubertänze",
  "Schwacher Astralkörper",
  "Schwacher Karmalkörper",
  "Sensibler Geruchssinn (*)",
  "Sprachfehler",
  "Stechender Orkgeruch (*)",
  "Stigma",
  "Stumm",
  "Taub",
  "Unfähig",
  "Unfrei",
  "Unpassender Name",
  "Unverträglichkeit gegenüber Alkohol",
  "Verminderte Zaubermelodien I-III",
  "Verminderte Zaubertänze I-III",
  "Verpflichtungen I-III",
  "Verstümmelt",
  "Verweichlicht",
  "Wahrer Name",
  "Wenige Predigten I-II",
  "Wenige Visionen I-II",
  "Wilde Magie",
  "Yurach",
  "Zauberanfällig I-II",
  "Zerbrechlich"
] as const;

